In [7]:
import pandas as pd
# pd. set_option('display.max_rows', None)

In [8]:
df = pd.read_csv("labels.csv", names=["original_filename", "label"])
df

              original_filename  label
0     1_IMG-20240731-WA0029.jpg    0.0
1     1_IMG-20240731-WA0030.jpg    2.0
2     1_IMG-20240809-WA0025.jpg    0.0
3     1_IMG-20240809-WA0038.jpg    0.0
4     1_IMG-20240812-WA0033.jpg    0.0
...                         ...    ...
3906   WhatsApp Image  (97).jpg    NaN
3907   WhatsApp Image  (98).jpg    NaN
3908   WhatsApp Image  (99).jpg    NaN
3909   WhatsApp Image  (9).jpeg    NaN
3910    WhatsApp Image  (9).jpg    NaN

[3911 rows x 2 columns]

In [9]:
df2 = pd.read_csv("images_rows.csv")
df2[["original_filename", "verdict"]]

                                    original_filename        verdict
0    1_WhatsApp Image 2024-09-25 at 20_46_23 (1).jpeg      compliant
1        1_WhatsApp Image 2024-09-05 at 17_27_41.jpeg      compliant
2    1_WhatsApp Image 2024-09-04 at 18_10_42 (1).jpeg            NaN
3        1_WhatsApp Image 2024-09-06 at 16_53_16.jpeg      compliant
4        1_WhatsApp Image 2024-09-05 at 20_18_12.jpeg            NaN
..                                                ...            ...
229      1_WhatsApp Image 2024-09-04 at 22_33_35.jpeg   needs_review
230                         1_IMG-20240911-WA0104.jpg   needs_review
231  1_WhatsApp Image 2024-09-25 at 19_39_22 (5).jpeg      compliant
232      1_WhatsApp Image 2024-09-04 at 17_09_33.jpeg  non_compliant
233  1_WhatsApp Image 2024-09-25 at 20_46_22 (1).jpeg  non_compliant

[234 rows x 2 columns]

In [10]:
df3 = pd.merge(df, df2, on='original_filename')
df3 = df3[["original_filename", "label", "verdict"]]
df3["predicted"] = df3[["verdict"]].apply(lambda x: [0.0 if y in ["needs_review"] else 2.0 if y in ["compliant"] else 0.0 for y in x])

In [11]:
df4 = df3.copy()
df4 = df4[(df4["predicted"] == 0.0) | (df4["predicted"] == 2.0)]
df4 = df4[(df4["label"] == 0.0) | (df4["label"] == 2.0)]
df4

,original_filename,label,verdict,predicted
0,1_IMG-20240731-WA0029.jpg,0.0,needs_review,0.0
1,1_IMG-20240731-WA0030.jpg,2.0,compliant,2.0
2,1_IMG-20240809-WA0025.jpg,0.0,needs_review,0.0
3,1_IMG-20240809-WA0038.jpg,0.0,non_compliant,0.0
4,1_IMG-20240812-WA0033.jpg,0.0,needs_review,0.0
...,...,...,...,...
246,1_WhatsApp Image 2024-09-25 at 20_58_20 (1).jpeg,2.0,compliant,2.0
247,1_WhatsApp Image 2024-09-25 at 20_58_20 (2).jpeg,0.0,compliant,2.0
248,1_WhatsApp Image 2024-09-25 at 20_58_21 (1).jpeg,2.0,compliant,2.0
249,1_WhatsApp Image 2024-09-25 at 20_58_22 (1).jpeg,2.0,compliant,2.0
250,1_WhatsApp Image 2024-09-25 at 20_58_22 (3).jpeg,0.0,NaN,0.0

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

y_true = df4['label']
y_pred = df4['predicted']

print(len(y_true))

# Individual metrics
accuracy  = accuracy_score(y_true, y_pred)

# Full report (includes F1-score + per-class breakdown)
print(classification_report(y_true, y_pred))

218
              precision    recall  f1-score   support

         0.0       0.91      0.93      0.92       155
         2.0       0.81      0.76      0.79        63

    accuracy                           0.88       218
   macro avg       0.86      0.85      0.85       218
weighted avg       0.88      0.88      0.88       218